[package]
name = "jito-searcher-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { workspace = true }
env_logger = { workspace = true }
jito-protos = { workspace = true }
log = { workspace = true }
jito-searcher-client = { workspace = true }
solana-client = { workspace = true }
solana-sdk = { workspace = true }
solana-commitment-config = { workspace = true }
solana-system-interface = { workspace = true }

tokio = { workspace = true, features = ["rt-multi-thread"] }
tonic = { workspace = true, features = ["tls-native-roots", "tls-webpki-roots"] }
