[package]
name = "jito-searcher-client"
version = "0.1.0"
edition = "2021"
description = "Wrapper around the generated gRPC. Adds auth and retry semantics."

[dependencies]
futures-util = "0.3.28"
jito-protos = { path = "../jito_protos" }
log = "0.4"
prost-types = "~0.14.0"
solana-client = "3.0.0"
solana-metrics = "3.0.0"
solana-sdk = "3.0.0"
solana-transaction-status = "3.0.0"
solana-nonce = "3.0.0"
solana-bincode = "3.0.0"
solana-program = "3.0.0"
solana-packet = "3.0.0"
solana-borsh = "3.0.0"
solana-tpu-client-next = "3.0.0"
solana-rpc-client-api = "3.0.0"
solana-transaction-status-client-types = "3.0.0"
agave-transaction-view = "3.0.0"
solana-svm-transaction = "3.0.0"
solana-commitment-config = "3.0.0"
thiserror = "1.0.40"
tokio = "1"
tonic = { version = "~0.14.2", features = ["tls-native-roots", "tls-webpki-roots"] }
