[package]
name = "jito-searcher-client"
version = "0.1.0"
edition = "2021"
description = "Wrapper around the generated gRPC. Adds auth and retry semantics."

[dependencies]
futures-util = { workspace = true }
jito-protos = { workspace = true }
log = { workspace = true }
prost-types = { workspace = true }
solana-client = { workspace = true }
solana-metrics = { workspace = true }
solana-sdk = { workspace = true }
solana-transaction-status = { workspace = true }
solana-nonce = { workspace = true }
solana-bincode = { workspace = true }
solana-program = { workspace = true }
solana-packet = { workspace = true }
solana-borsh = { workspace = true }
solana-tpu-client-next = { workspace = true }
solana-rpc-client-api = { workspace = true }
solana-transaction-status-client-types = { workspace = true }
agave-transaction-view = { workspace = true }
solana-svm-transaction = { workspace = true }
solana-commitment-config = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tonic = { workspace = true, features = ["tls-native-roots", "tls-webpki-roots"] }
bytes = "1.11.1"
